import React from 'react'
import Loader from '../components/Loader'
import FormFields from '../components/FormFields'
import { useState } from 'react'

const Home = () => {
          const [loading, setLoading] = useState(false)
    const [searchText, setSearchText] = useState("")
    const [allPost, setAllPost] = useState(null)
    const RenderCards = ({data,title}) => {
        if (data?.length > 0) {
            data.map((post) => {
                return <Card key={ post._id} {...post} />
            })
        }
        return (<div className='text-blue-500 text-xl my-10'>
           {title} 
        </div>)
    }
    
  return (
    <div className='max-w-7xl mx-auto'>
          <h1 className='text-2xl font-bold'>The Community Showcase</h1>
          <p className='text-xs text-neutral-500 py-2'>Have a Sight of visual and beautifull images generated by DALL-E 2.0 AI </p>
          <div className='mt-16'>
            <FormFields/>
          </div>
          {
              loading ? (<div className=' flex justify-center mt-10'>
                  <Loader/>
              </div>)
                  : (<>
                  
                      {searchText && (
                          <div className='text-lg'>result found for "<p className='text-neutral-500 inline'>{ searchText}"</p></div>
                      )}
                      <div className='grid lg:grid-cols-4 sm:grid-col-3 xs:grid-col-2 grid-col-1 gap-3'>
                          {
                              searchText ? (
                                  <RenderCards data={"" } title={"no Search result found"} />
                              ) : (
                                  <RenderCards data={""} title={"no Post found"} />
                                      
                             )
                          }
                      </div>
                  </>
                  
                  )
      }
    </div>
  )
}

export default Home
